package cc.asylum.iridium.data;

import cc.asylum.iridium.data.config.DataSettings;
import org.babyfish.jimmer.sql.JSqlClient;
import org.babyfish.jimmer.sql.ast.query.specification.JSpecification;
import org.babyfish.jimmer.sql.ast.query.specification.SpecificationArgs;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class RepositoryTest {

  @Test
  void savesFindsAndFilters() throws Exception {
    final DataSettings settings = DataSettings.of("jdbc:h2:mem:books;DB_CLOSE_DELAY=-1");
    final DataSource dataSource = DataClients.dataSource(settings);
    try (Connection connection = dataSource.getConnection();
         Statement statement = connection.createStatement()) {
      statement.execute("""
          create table book (
            id bigint generated by default as identity primary key,
            name varchar(100) not null,
            price decimal(10, 2) not null
          )
          """);
      final JSqlClient sql = DataClients.sqlClient(dataSource, settings);
      final BookRepository books = new BookRepository(sql);
      final Book saved = books.save(BookDraft.$.produce(draft -> {
        draft.setName("Iridium");
        draft.setPrice(new BigDecimal("12.50"));
      }));
      books.save(BookDraft.$.produce(draft -> {
        draft.setName("Other");
        draft.setPrice(new BigDecimal("3.00"));
      }));

      assertNotNull(saved.id());
      assertEquals("Iridium", books.findById(saved.id()).name());
      assertEquals(2, books.count());

      final List<Book> matched = books.findAll(new JSpecification<Book, BookTable>() {
        @Override
        public Class<Book> entityType() {
          return Book.class;
        }

        @Override
        public void applyTo(final SpecificationArgs<Book, BookTable> args) {
          args.where(args.getTable().name().likeIf("Iri"));
        }
      });
      assertEquals(1, matched.size());
      assertEquals(saved.id(), matched.get(0).id());
      assertEquals(1, books.page(null, 0, 1).content().size());
      assertEquals(2, books.page(null, 0, 1).pages());
      assertEquals(2, books.count(null));
      assertEquals(0, books.page(new JSpecification<Book, BookTable>() {
        @Override
        public Class<Book> entityType() {
          return Book.class;
        }

        @Override
        public void applyTo(final SpecificationArgs<Book, BookTable> args) {
          args.where(args.getTable().name().eq("missing"));
        }
      }, 0, 5).content().size());
      assertNull(books.findOne(new JSpecification<Book, BookTable>() {
        @Override
        public Class<Book> entityType() {
          return Book.class;
        }

        @Override
        public void applyTo(final SpecificationArgs<Book, BookTable> args) {
          args.where(args.getTable().name().eq("missing"));
        }
      }));
      assertEquals(2, books.findAll(null, 0, 0).size());
    } finally {
      if (dataSource instanceof final AutoCloseable closeable) {
        closeable.close();
      }
    }
  }

  @Test
  void rejectsInvalidPagesWithoutADatabase() {
    final BookRepository books = new BookRepository(null);
    assertThrows(IllegalArgumentException.class, () -> books.page(null, -1, 1));
    assertThrows(IllegalArgumentException.class, () -> books.page(null, 0, 0));
  }
}
