plugins {
    id 'cc.asylum.iridium'
}

group = 'cc.asylum.iridium.demo.hello'

application {
    mainClass = 'cc.asylum.iridium.demo.hello.Application'
}

dependencies {
    implementation project(':iridium-openapi')
    runtimeOnly project(':iridium-hot-reloading')
}

tasks.named('run') {
    def agent = project(':iridium-hot-reloading').tasks.named('jar')
    dependsOn agent
    jvmArgs "-javaagent:${agent.get().archiveFile.get().asFile.absolutePath}"
}
